build:
	(cd go1.2.2_protoc2.3.0 && make build)
	(cd go1.2.2_protoc2.4.1 && make build)
	(cd go1.2.2_protoc2.5.0 && make build)
	(cd go1.3_protoc2.3.0 && make build)
	(cd go1.3_protoc2.4.1 && make build)
	(cd go1.3_protoc2.5.0 && make build)
run:
	(cd go1.2.2_protoc2.3.0 && make run)
	(cd go1.2.2_protoc2.4.1 && make run)
	(cd go1.2.2_protoc2.5.0 && make run)
	(cd go1.3_protoc2.3.0 && make run)
	(cd go1.3_protoc2.4.1 && make run)
	(cd go1.3_protoc2.5.0 && make run)